<?php

namespace zbiorDanychBundle\Repository;

/**
 * kategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
