<?php

namespace zbiorDanychBundle\Repository;

/**
 * wpisyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wpisyRepository extends \Doctrine\ORM\EntityRepository
{
}
